// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXeuro4rpl7Pmw5Jd54F2wJj6Mof-xjHo',
    appId: '1:654324791516:web:6f249407be3aef420e1c19',
    messagingSenderId: '654324791516',
    projectId: 'e-store-60ad6',
    authDomain: 'e-store-60ad6.firebaseapp.com',
    storageBucket: 'e-store-60ad6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDf_7PoqRZ9UzUHlH3XOZQUkL8QndO2t8',
    appId: '1:654324791516:android:18b06b0d868baa190e1c19',
    messagingSenderId: '654324791516',
    projectId: 'e-store-60ad6',
    storageBucket: 'e-store-60ad6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSBR82vuYt1aq0PwvPxl0KbZnwMV5NdQ4',
    appId: '1:654324791516:ios:4165d727158a913a0e1c19',
    messagingSenderId: '654324791516',
    projectId: 'e-store-60ad6',
    storageBucket: 'e-store-60ad6.appspot.com',
    androidClientId: '654324791516-7jce96rn9ngqcdu9uan9d4omabbdkig0.apps.googleusercontent.com',
    iosClientId: '654324791516-7m3o51teq87dm1mnsq3s079bljnj4lbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.estore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXeuro4rpl7Pmw5Jd54F2wJj6Mof-xjHo',
    appId: '1:654324791516:web:23d809ab8639d5080e1c19',
    messagingSenderId: '654324791516',
    projectId: 'e-store-60ad6',
    authDomain: 'e-store-60ad6.firebaseapp.com',
    storageBucket: 'e-store-60ad6.appspot.com',
  );

}